### ISSUE TITLE
Stock price not updating

### ISSUE THREAD

**Issue by kintonc** [shayne/stock-ticker-stream-deck-plugin#18] opened 2023-04-20 14:03 UTC
As of yesterday morning, the plugin no longer shows stock price.

This is what I see:

![image](https://user-images.githubusercontent.com/32663075/233390506-d4008305-b400-455f-ab39-3cf492bce671.png)

I've tried changing tickers (SPY, DIA, QQQ), deleting and readding the icons, and uninstalling / reinstalling the plugin, but still the same result.

**Comment by Grandbassist1209** [comment] 2023-04-20 14:18
Also seeing the same problem with no found workaround at the moment.

**Comment by zariok** [comment] 2023-04-26 02:26
The problem is in cmd/stock_ticker_stream_deck_plugin/api.go .  There are several log.Fatal calls on err which will cause the cmd to exit if the network request fails or the query1.finance.yahoo.com domain is unavailable.  You will have to remove your entry via "delete" and re-add it OR full exit streamdeck and reload when network is available.  This could be fixed up with some better handling and a logarithmic back-off of retries (e.g. 5s, 10s, 30s.. etc)

**Comment by shayne** [comment] 2023-05-06 16:29
Fixed in [v1.1.3](https://github.com/shayne/stock-ticker-stream-deck-plugin/releases/tag/v1.1.3)

**Closed by shayne** 2023-05-06 16:29 UTC
